from common import *
import efficiency_figures as efficiency

def build():
 from learning import build as build_learning
 build_learning()
 body=sec('generalization','汎化：訓練していない例で使えるか',p('汎化（generalization）は、訓練データ以外でも役立つ予測ができることです。訓練誤差を下げる力だけでなく、データ量、モデルの仮定、正則化、データ分布などが関わります。訓練と未知データの性能差を、何が決めるのか自体が研究対象です。')+img('reliability.svg','訓練と検証の曲線、および学習率による更新の比較','教材用の概念図。左は訓練への適合と汎化の違い、右は一変数の損失に対する更新の違い。実測の学習ログではない。')+p('検証データでモデルや設定を選び、最終評価は別のテストデータで行います。何度も見て調整したデータを、手つかずの未知データとは扱えません。同じ分布内の汎化と、環境の違うデータへの汎化も区別します。'))
 body+=sec('optimization','最適化：損失を、どう下げるか',eq('\\theta_{t+1} = \\theta_t - \\eta\\nabla L(\\theta_t)','ηは学習率。勾配はその場所で損失が増える方向を示すため、逆へ進む。SGDのミニバッチでは全データの勾配を近似する。')+p('損失L(w)=w²なら勾配は2w。w=2でη=0.1なら次は1.6、η=1.1なら−2.4となり、最小点を越えてさらに遠くへ進みます。MomentumやAdamは過去の勾配・成分ごとの尺度を使って更新を工夫します。速く訓練損失を下げることと、良く汎化することは同じ問いではありません。')+'<figure class="optimization-video"><video controls playsinline loop preload="metadata" poster="assets/optimization-descent-poster.jpg" aria-label="3Dの損失地形を点が下る最適化の動画"><source src="assets/optimization-descent.webm" type="video/webm">動画を再生できません。</video><figcaption><strong>山の高さ＝損失。地形上の点＝現在のパラメータ。</strong><br>横方向の二つの座標を更新すると、点が斜面を下り、損失の小さい谷へ近づきます。色の違う軌跡はSGD・Momentum・RMSProp・Adamによる進み方の違い、下のグラフは更新に伴う損失の変化です。二変数の関数で最適化を可視化した例で、どの方法が速いかは地形や学習率によって変わります。<br>出典：'+ref('https://github.com/ajithpinninti/gradient-descent-visualizer','Ajith Pinninti — Gradient Descent Visualizer')+'（MIT）。</figcaption></figure>')
 body+=sec('robustness','頑健性：条件が変わっても精度を保つ',p('頑健性（robustness）は、入力の条件が変わっても、予測の精度が大きく下がらない性質です。同じ対象でも、暗さ、雨、背景、カメラなどが変わります。こうした自然な分布変化（distribution shift）と、モデルを誤らせる目的で作った摂動（adversarial perturbation）を分けます。どの変化に強いかを定義して初めて「頑健」と評価できます。')+'<div class="demo" data-demo="brightness"><strong>同じ画像の撮影条件を変える</strong><label>明るさ <input type="range" min="0.2" max="1.8" step="0.1" value="1"></label><img src="assets/gradcam-original.png" alt="明るさを変えて観察する猫と犬の共通写真" width="240"><p class="result">暗くなっても、写っている猫や犬は同じです。撮影条件が変わっても正しく認識できるようにし、モデルの精度の低下を抑えることが頑健性の目標です。</p></div>'+p('たとえば、明るさやぼけを変えた画像も訓練に加える「データ拡張」で、見え方の違いに慣れさせます。利用先の環境に合わせて学び直す「分布適応」も方法の一つです。そのうえで、暗い画像や別のカメラで撮った未学習の画像を使い、条件ごとの正解率と、通常の画像からどれだけ精度が下がったかを確かめます。'))
 body+=sec('uncertainty','不確実性：分からなさを表す',table(['種類','具体例','考える方法'],[('データ由来の曖昧さ / aleatoric','ぼけた画像で3と8を区別しにくい、観測にノイズ','出力分布や予測区間。データを増やしても観測の曖昧さが残ることがある'),('モデルの知識不足 / epistemic','学習に出なかった撮影条件・分子構造','複数モデルの不一致、ベイズ的な推定など。新しいデータで減らせる場合がある')])+p('この二つを実際のモデルで完全に切り分けられるとは限りません。分類のsoftmaxの最大値が高いだけで、知識が十分とは言えません。回帰なら一点だけでなく幅を持つ予測を出し、その幅がどれだけ観測を覆うかを評価します。'))
 body+=refs([('Deep Ensembles：予測の不確実性','https://arxiv.org/abs/1612.01474'),('Explaining and Harnessing Adversarial Examples','https://arxiv.org/abs/1412.6572')])
 page('reliability','汎化・最適化・頑健性・不確実性','横断的な研究','04 / LEARNING BEHAVIOR & RELIABILITY','学習できること、未知の例に使えること、条件の変化に耐えること、分からなさを表すこと。それぞれ異なる研究の問いです。',body)
 from xai import build as build_xai
 build_xai()
 body=sec('cost','高い性能のAIを、少ない資源で使うには',p('AIの性能を高めるためにモデルを大きくすると、計算やメモリの負担も増えます。そこで、<strong>能力をできるだけ保ちながら、保存・実行・追加学習を軽くする</strong>工夫が必要になります。'))
 body+=sec('distillation','蒸留：大きなモデルから小さなモデルへ',p('<strong>大きなモデルの予測を手本に、小さなモデルを育てます。</strong>同じ入力への予測確率を近づけるように学習し、利用時は小さなモデルだけを使います。')+efficiency.distillation())
 body+=sec('quantization','量子化：モデルの中の数値を丸める',p('<strong>重みや途中の値を少ないビットで表し、メモリを減らします。</strong>細かい違いを省く分、予測の正確さが下がることもあります。')+efficiency.quantization()+p('重みを32 bitから8 bitにすると、10億個の重み本体は<strong>約4 GB → 約1 GB</strong>。倍率などの追加情報や、途中の値のメモリは別です。')+sub('表せる範囲と、数値の細かさ',p('十進数で4桁 → 3桁に減らす説明例です。')+bullets(['<strong>範囲をほぼ保つ：</strong>最大99.99 → 99.9。12.34は12.3へ丸める。','<strong>細かさを保つ：</strong>最大99.99 → 9.99。1.23はそのまま、12.34は範囲外。'])+p('数値の丸めや範囲外の値の扱いが、予測にどう影響するかを確認します。')))
 body+=sec('lora','LoRA：小さな追加部品で用途に合わせる',p('大きなモデル全体を学習し直すのは大変です。LoRAでは、<strong>元のモデルを固定し、小さな追加部品だけを学習</strong>して、新しい用途に合わせます。')+efficiency.lora()+p('軽くなるのは主に追加学習の負担です。利用時にも元のモデルは必要です。'))
 body+=sec('systems','計算の仕方も工夫する',table(['工夫','やりたいこと'],[('枝刈り','不要な重みや計算部分を削る'),('MoE','入力に応じて、担当する一部のモデルだけを使う'),('データ並列','複数のGPUで、データを分担して学習する'),('モデル並列','大きなモデルを複数のGPUに分けて載せる'),('Attentionの実装改善','メモリの読み書きを減らし、同じ計算を速くする')])+p('実際に速くなるかは、装置や入力条件をそろえて測ります。'))
 body+=refs([('知識蒸留','https://arxiv.org/abs/1503.02531'),('整数量子化の研究例','https://arxiv.org/abs/1712.05877'),('LoRA','https://arxiv.org/abs/2106.09685'),('FlashAttention','https://arxiv.org/abs/2205.14135')])
 page('efficiency','効率化・システム — 少ない資源で動かす','横断的な研究','04 / EFFICIENT ML & SYSTEMS','同じ能力をできるだけ保ちながら、学習・保存・実行のどこを軽くするか。蒸留、量子化、LoRAを図で比べます。',body)
